
global:
  REDIS_HOST: redis
  REDIS_PORT: 6379
  REDIS_CHANNEL:
  REDIS_PASSWORD:

plugin:
  image: public.ecr.aws/h7r1e4h2/cookbook-redis-service
  tag: latest
  NTS_HOST: nts.nanome.ai
  NTS_PORT: 8888
  NTS_KEY: 6EFAA5017FB93C038
  PLUGIN_VERBOSE: true
  PLUGIN_WRITE_LOG_FILE: true
  PLUGIN_REMOTE_LOGGING: false
  DEFAULT_URL: http://a372db549edd54c70a72f66db0ee0008-334333203.us-west-1.elb.amazonaws.com:8888
  PLUGIN_NAME: Cookbook

jupyter_notebook:
  image: public.ecr.aws/h7r1e4h2/cookbook
  tag: latest
  JUPYTER_TOKEN:
