image: public.ecr.aws/h7r1e4h2/data-table
tag: latest

global:
  NTS_HOST:
  NTS_PORT:
  NTS_KEY:
  PLUGIN_VERBOSE:
  PLUGIN_WRITE_LOG_FILE: True
  PLUGIN_REMOTE_LOGGING: False

ENV:
  SERVER_URL: 127.0.0.1

data_table_server:
  image: public.ecr.aws/h7r1e4h2/data-table-server
  tag: latest
